### ISSUE TITLE
boost update 1.65.1

### ISSUE THREAD

**Issue by thierry3000** [DaWelter/numpycpp#1]
According to the changelog of the boost library the name python::numeric api has been deleted.

> The boost::python::numeric API has been removed, as it is being obsoleted by boost::python::numpy. 

Therefore the demo is not usable anymore. I tried to update the affected lines in my fork, but ran into the following segmentation fault:

> GNU gdb (GDB) 8.0.1
> Copyright (C) 2017 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-pc-linux-gnu".
> Type "show configuration" for configuration details.
> For bug reporting instructions, please see:
> <http://www.gnu.org/software/gdb/bugs/>.
> Find the GDB manual and other documentation resources online at:
> <http://www.gnu.org/software/gdb/documentation/>.
> For help, type "help".
> Type "apropos word" to search for commands related to "word"...
> Reading symbols from python2...(no debugging symbols found)...done.
> (gdb) run demo.py
> Starting program: /usr/bin/python2 demo.py
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/usr/lib/libthread_db.so.1".
> VARIOUS TYPES MAPPING:
> -----<type 'object'>-------
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007fffef6991ba in boost::python::converter::object_manager_traits<boost::python::numpy::ndarray>::get_pytype() () from /usr/lib/libboost_numpy.so.1.65.1
> (gdb) bt
> #0  0x00007fffef6991ba in boost::python::converter::object_manager_traits<boost::python::numpy::ndarray>::get_pytype() ()
>    from /usr/lib/libboost_numpy.so.1.65.1
> #1  0x00007fffefb83d92 in boost::python::converter::object_manager_traits<boost::python::numpy::ndarray>::check (x=0x7fffefdcbd50)
>     at /usr/include/boost/python/numpy/ndarray.hpp:309
> #2  0x00007fffefb8d61b in boost::python::converter::object_manager_value_arg_from_python<boost::python::numpy::ndarray>::convertible (this=0x7fffffffd9a0)
>     at /usr/include/boost/python/converter/obj_mgr_arg_from_python.hpp:69
> #3  0x00007fffefb8d17f in boost::python::detail::caller_arity<2u>::impl<void (*)(boost::python::numpy::ndarray, bool), boost::python::default_call_policies, boost::mpl::vector3<void, boost::python::numpy::ndarray, bool> >::operator() (
>     this=0x55555582df58, args_=0x7ffff7e64998)
>     at /usr/include/boost/preprocessor/iteration/detail/local.hpp:34
> #4  0x00007fffefb8bd67 in boost::python::objects::caller_py_function_impl<boost::python::detail::caller<void (*)(boost::python::numpy::ndarray, bool), boost::python::default_call_policies, boost::mpl::vector3<void, boost::python::numpy::ndarray, bool> > >::operator() (this=0x55555582df50, args=0x7ffff7e64998, kw=0x0)
>     at /usr/include/boost/python/object/py_function.hpp:38
> #5  0x00007fffef8c20cd in boost::python::objects::function::call(_object*, _object*) const () from /usr/lib/libboost_python.so.1.65.1
> #6  0x00007fffef8c2289 in ?? () from /usr/lib/libboost_python.so.1.65.1
> #7  0x00007fffef8c8e53 in boost::python::handle_exception_impl(boost::function0<---Type <return> to continue, or q <return> to quit---
> void>) () from /usr/lib/libboost_python.so.1.65.1
> #8  0x00007fffef8bf8ba in ?? () from /usr/lib/libboost_python.so.1.65.1
> #9  0x00007ffff74cdd93 in PyObject_Call () from /usr/lib/libpython2.7.so.1.0
> #10 0x00007ffff74aac6e in PyEval_EvalFrameEx ()
>    from /usr/lib/libpython2.7.so.1.0
> #11 0x00007ffff7504886 in PyEval_EvalCodeEx ()
>    from /usr/lib/libpython2.7.so.1.0
> #12 0x00007ffff751a05a in PyEval_EvalCode () from /usr/lib/libpython2.7.so.1.0
> #13 0x00007ffff75217f1 in run_mod () from /usr/lib/libpython2.7.so.1.0
> #14 0x00007ffff75230d5 in PyRun_FileExFlags ()
>    from /usr/lib/libpython2.7.so.1.0
> #15 0x00007ffff75232aa in PyRun_SimpleFileExFlags ()
>    from /usr/lib/libpython2.7.so.1.0
> #16 0x00007ffff7511863 in Py_Main () from /usr/lib/libpython2.7.so.1.0
> #17 0x00007ffff7823f6a in __libc_start_main () from /usr/lib/libc.so.6
> #18 0x000055555555478a in _start ()

Since I am not a python hero, any help is welcomed.

**Comment by thierry3000** [comment]
added preprocesor makros to restore old behavior based on boost version.
